Feat/get data for statistics and display them
FppEpitech/Survivor pull request #122
Opened 2024-09-06 18:45 UTC by mathieurobert1

I recreate entirely the statistics page with ngx charts to create graphs.

I displayed different information about company (nb customers, employee, etc...).

![image](https://github.com/user-attachments/assets/15774cbe-0035-4fcc-9c54-5185db975315)

2024-09-06 18:49 UTC, Njord201 requested changes
One little request (chore), good job !

2024-09-06 18:49 UTC, Njord201 commented on angular-frontend/src/app/app.module.ts
> +// import { NgxChartsModule } from 'ngx-charts';
Remove this line ?

2024-09-06 19:30 UTC, theophile-jr submitted a review, later dismissed

2024-09-08 21:25 UTC, Njord201 approved these changes

2024-09-09 07:05 UTC, AxelF44 approved these changes

2024-09-09 07:19 UTC, AxelF44 approved these changes

2024-09-09 07:19 UTC, theophile-jr approved these changes

2024-09-09 07:28 UTC, Njord201 approved these changes

2024-09-09 07:34 UTC, merged