feat: securize assets
FppEpitech/Survivor pull request #137
Opened 2024-09-09 15:16 UTC by theophile-jr

Add the middle ware to assets/

2024-09-09 15:17 UTC, mathieurobert1 requested changes

2024-09-09 15:17 UTC, mathieurobert1 commented on express-backend/prisma/fetchData/fetchAndStoreData.ts
> +        // await fetchClothes(token);
delete comments

2024-09-10 06:56 UTC, AxelF44 requested changes

2024-09-10 06:56 UTC, AxelF44 commented on express-backend/prisma/fetchData/fetchAndStoreData.ts
> +        // await fetchClothes(token);
```suggestion
        await fetchTips(token);
        await fetchClothes(token);
```

2024-09-10 08:11 UTC, Njord201 approved these changes

2024-09-10 08:41 UTC, Njord201 submitted a review, later dismissed

2024-09-10 08:41 UTC, AxelF44 approved these changes

2024-09-10 08:42 UTC, mathieurobert1 approved these changes

2024-09-10 08:50 UTC, theophile-jr commented
This pull request is being closed due to the fact that the issue was fixed in another branch.

2024-09-10 08:50 UTC, closed without merging