Feat/create customer creation page
FppEpitech/Survivor pull request #200
Opened 2024-09-11 22:52 UTC by mathieurobert1

I created the customer creation page.
![image](https://github.com/user-attachments/assets/f5ce7c89-76c3-4158-a1ee-9f0a9ecb6800)

2024-09-11 22:54 UTC, theophile-jr submitted a review, later dismissed

2024-09-11 22:58 UTC, Njord201 requested changes

2024-09-11 22:58 UTC, Njord201 commented on angular-frontend/src/app/pages/customers-list/customers-list.component.html
> +                    </td> -->
Remove the comment.

2024-09-11 22:58 UTC, Njord201 commented on angular-frontend/src/app/pages/customers-list/customers-list.component.ts
> +        // }
Remove the comment.

2024-09-11 22:58 UTC, Njord201 commented on angular-frontend/src/app/pages/register-customer/register-customer.component.html
> +        </div>
We can't define the astrological sign automatically ?

2024-09-12 06:46 UTC, mathieurobert1 commented on angular-frontend/src/app/pages/customers-list/customers-list.component.html
> +                    </td> -->
It's to wait the new Axel's feature about method payments.

2024-09-12 06:46 UTC, mathieurobert1 commented on angular-frontend/src/app/pages/customers-list/customers-list.component.ts
> +        // }
It's to wait the new Axel's feature about method payments.

2024-09-12 06:47 UTC, mathieurobert1 commented on angular-frontend/src/app/pages/register-customer/register-customer.component.html
> +        </div>
If you have an idea to compute signs based on birth date, give me your ideas

2024-09-12 07:30 UTC, theophile-jr approved these changes

2024-09-12 07:36 UTC, Njord201 requested changes
Check my comment.

2024-09-12 10:43 UTC, theophile-jr approved these changes

2024-09-12 10:54 UTC, Njord201 approved these changes

2024-09-12 11:28 UTC, merged